In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import scipy as sp
import requests
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [2]:
df_weather = pd.read_csv("external_data.csv")

In [3]:
df_weather2 = pd.read_csv("external_data8.csv")

In [4]:
df_weather

,Unnamed: 0,date,Temperature (C),wind_dir,wind_speed,Humidity,Visibility,Precipitation,pressure1,sunshine_time,suntime,new_cases,holidays2
0,0,01-09-2020 23:00,14.9,NNE,5.6,63,20.0,0,1019.1,21960,48255,5104.0,0
1,1,01-09-2020 22:00,15.2,NNE,5.6,59,20.0,0,1019.0,21960,48255,5104.0,0
2,2,01-09-2020 21:00,16.4,NE,7.4,52,20.0,0,1018.9,21960,48255,5104.0,0
3,3,01-09-2020 20:00,17.1,NNE,7.4,49,20.0,0,1018.5,21960,48255,5104.0,0
4,4,01-09-2020 19:00,18.5,NNE,5.6,46,20.0,0,1017.9,21960,48255,5104.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11549,11552,31-12-2021 04:00,9.0,S,5.6,96,19.0,0,1021.5,21960,29965,232200.0,0
11550,11553,31-12-2021 03:00,9.5,S,11.1,96,20.0,0,1021.4,21960,29965,232200.0,0
11551,11554,31-12-2021 02:00,9.6,SO,5.6,96,11.0,0,1022.0,21960,29965,232200.0,0
11552,11555,31-12-2021 01:00,10.3,S,7.4,96,10.0,0,1022.0,21960,29965,232200.0,0
11553,11556,31-12-2021 00:00,10.8,S,11.1,96,14.0,2,1022.2,21960,29965,232200.0,0

In [5]:
df_weather2

,Unnamed: 0,date,Temperature (C),wind_dir,wind_speed,Humidity,Visibility,Precipitation,pressure1,sunshine_time,suntime,date_only,new_cases
0,0,2020-09-01 23:00:00,14.9,NNE,5.6,63.0,20.0,0,1019.1,21960.0,48255.0,2020-09-01,5104.0
1,1,2020-09-01 22:00:00,15.2,NNE,5.6,59.0,20.0,0,1019.0,21960.0,48255.0,2020-09-01,5104.0
2,2,2020-09-01 21:00:00,16.4,NE,7.4,52.0,20.0,0,1018.9,21960.0,48255.0,2020-09-01,5104.0
3,3,2020-09-01 20:00:00,17.1,NNE,7.4,49.0,20.0,0,1018.5,21960.0,48255.0,2020-09-01,5104.0
4,4,2020-09-01 19:00:00,18.5,NNE,5.6,46.0,20.0,0,1017.9,21960.0,48255.0,2020-09-01,5104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11552,11552,2021-12-31 04:00:00,9.0,S,5.6,96.0,19.0,0,1021.5,21960.0,29965.0,2021-12-31,232200.0
11553,11553,2021-12-31 03:00:00,9.5,S,11.1,96.0,20.0,0,1021.4,21960.0,29965.0,2021-12-31,232200.0
11554,11554,2021-12-31 02:00:00,9.6,SO,5.6,96.0,11.0,0,1022.0,21960.0,29965.0,2021-12-31,232200.0
11555,11555,2021-12-31 01:00:00,10.3,S,7.4,96.0,10.0,0,1022.0,21960.0,29965.0,2021-12-31,232200.0
11556,11556,2021-12-31 00:00:00,10.8,S,11.1,96.0,14.0,2,1022.2,21960.0,29965.0,2021-12-31,232200.0

In [10]:
df_weather2.columns[df_weather.columns != df_weather2.columns]

Index(['date_only', 'new_cases'], dtype='object')

In [11]:
df_weather2.new_cases

0          5104.0
1          5104.0
2          5104.0
3          5104.0
4          5104.0
           ...
11552    232200.0
11553    232200.0
11554    232200.0
11555    232200.0
11556    232200.0
Name: new_cases, Length: 11557, dtype: float64

In [12]:
df_weather.new_cases

0          5104.0
1          5104.0
2          5104.0
3          5104.0
4          5104.0
           ...
11549    232200.0
11550    232200.0
11551    232200.0
11552    232200.0
11553    232200.0
Name: new_cases, Length: 11554, dtype: float64

## _Model6_

In [ ]:
    params = {'learning_rate': 0.15, 'max_depth': 10, 'l2_leaf_reg': 10,
              'iterations': 900, 'max_bin': 280, 'bagging_temperature': 1, 'random_strength': 10, 'task_type': 'GPU'}

Mean CV scores
----------------------------
        score             rmse          time
        train  0.313 +- 0.0304  12.7 +- 2.07
        valid   0.698 +- 0.092   2.5 +- 0.09
        test   0.681 +- 0.0758   0.9 +- 0.01
----------------------------
Bagged scores
----------------------------
        score   rmse
        valid  0.704
        test   0.566

## _Model7_

In [ ]:
params = {'learning_rate': 0.15, 'max_depth': 11, 'l2_leaf_reg': 10,
              'iterations': 900, 'max_bin': 280, 'bagging_temperature': 1, 'random_strength': 10, 'task_type': 'GPU'}

Mean CV scores
----------------------------
        score             rmse          time
        train  0.299 +- 0.0309  16.7 +- 2.32
        valid   0.702 +- 0.086   2.6 +- 0.03
        test   0.673 +- 0.0771   0.9 +- 0.02
----------------------------
Bagged scores
----------------------------
        score   rmse
        valid  0.708
        test   0.561